name: Run Continous Integration Pipeline

on:
  workflow_dispatch:
  repository_dispatch:
    types:
      - continuous-integration

permissions:
  id-token: write
  contents: read

jobs:
  integration:
    name: Continuous Integration
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Lint code
        run: echo "Linting repository"

      - name: Run unit tests
        run: echo "Running unit tests"

  delivery:
    name: Continuous Delivery
    runs-on: ubuntu-latest
    needs: integration
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Build and push kfp components
        run: make build_components
